### ISSUE TITLE
Both versions do not work on my machine, 1.1 .cor file also seems broken

### ISSUE THREAD

**Issue by Kugelblitz360** [zeldin/Mega99#3]
Both versions do not even give a signal on HDMI out after booting. (All files are both in root in mega99 dir).

Version 1.1 cor file does not flash correctly. It flashes one block, then skips across a number of blocks, then writes another block. The 1.0 cor file flashes all through (but still does not work).

Thank you, Boris (cores.mega65.org)

**Comment by Kugelblitz360** [comment]
The HDMI output is incompatible with my HDMI grabber card. Directly connecting the monitor to the MEGA65 has worked,

**Comment by zeldin** [comment]
Yeah, the HDMI signal is slighly different from a standard 480p signal because it is based on TMS9918 video timing.  With piKVM I get a picture (this is how I took the screenshots on the filehost) but it jumps up and down a lot. :smile:
Any computer monitor should be able to handle it just fine, and probably most TV sets as well.
